name: Daily Commit Streak
on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for proper git history
      - name: Create or update daily.md
        run: echo "Last commit: $(date -u)" >> daily.md
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily.md
          git diff --quiet && git diff --cached --quiet || git commit -m "Daily commit for streak [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
